2captcha:
  api_key: null
api:
  access_token:
  code:
  refresh_token:
database:
  host: null
  name: receipt.db
  password: null
  type: sqlite
  username: null
dpi: 300
receipt:
  first-word: aantal
  last-word: totaal
  pixel-distance: 50
tesseract:
  psm:
    price: 12
    receipt: 6
