2captcha:
  api_key: null
api:
  access_token:
  code:
  refresh_token:
database:
  path: receipt.db
  type: sqlite
dpi: 300
receipt:
  first-word: aantal
  last-word: totaal
  pixel-distance: 50
tesseract:
  psm:
    price: 12
    receipt: 6
