2captcha:
  api_key: null
api:
  access_token: 273392689_ecc-4fb1-9265-3e0348338e29
  code: 0477766a-c2ba-4751-ab18-ce4f354327fb
  refresh_token: 2b738b59-d0e0-46d2-be66-7f96506d1af1
database:
  host: 10.10.194.5
  name: receipt-scanner
  password: isTheBest
  type: sqlite
  username: receipt-scanner
dpi: 300
receipt:
  first-word: aantal
  last-word: totaal
  pixel-distance: 50
tesseract:
  psm:
    price: 12
    receipt: 6
