version: "3.8"

services:
  grocitrack:
    build: .
    container_name: grocitrack
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - grocitrack
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: postgres-grocitrack
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: grocitrack
    ports:
      - "5432:5432"
    networks:
      - grocitrack

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - grocitrack

networks:
  grocitrack:
